---
# This playbook will install MariaDB and create db user and give permissions.

- name: Add Adam's SSH key
  authorized_key: 
    user: root
    key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDj1OFnrboalGp+OqYeuKTjzpkUSLGfOnsC/AsLodw5dD45IaB5AP6vLO6FrcHU1iyOe3U/ND5lRmo4REBLhEXzelPiFQ4/ScsZV/p3+WJ932HTa7EVnYyE2wMKe6+tmerz2U6co0NNbD0X+Dw9sTQ84wFF7oAmMhhADVF2mwCMAEGP2XyOi1eHDsLRedwAoBbuxQx/WMjqhvgJPj5pas5xUpPU9cmNldXXgqpLtrTut8PapnqcsCyDVILC28m/T5l7SA3YBd7X77ZHLghcGhh9SpqBjRsH5pvrrvdHyJFmFl3hbcNen8Q00tEs0jgYAU4oOM84gts1JSEuHkT/0MnB amclean@dhcp-32-46.ord.redhat.com"

- name: Install MariaDB package
  yum: name={{ item }} state=installed
  with_items:
   - mariadb-server
   - MySQL-python
   - libselinux-python
   - libsemanage-python

- name: Configure SELinux to start mysql on any port
  seboolean: name=mysql_connect_any state=true persistent=yes

- name: Create Mysql configuration file
  template: src=my.cnf.j2 dest=/etc/my.cnf
  notify: 
  - restart mariadb
  
- name: Create MariaDB log file
  file: path=/var/log/mysqld.log state=touch owner=mysql group=mysql mode=0775
  
- name: Create MariaDB PID directory
  file: path=/var/run/mysqld state=directory owner=mysql group=mysql mode=0775

- name: Start MariaDB Service
  service: name=mariadb state=started enabled=yes

- name: insert firewalld rule
  firewalld: port={{ mysql_port }}/tcp permanent=true state=enabled immediate=yes

- name: Create Application Database
  mysql_db: name={{ dbname }} state=present

- name: Create Application DB User
  mysql_user: name={{ dbuser }} password={{ upassword }} priv=*.*:ALL host='%' state=present
